- name: Importación de claves del repo Kubic
  ansible.builtin.apt_key:
  url:  https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key
  keyring: /usr/share/keyrings/libcontainers-archive-keyring.gpg
  state: present

- name: Importación de claves del repo CRI-O
  ansible.builtin.apt_key:
  url:  https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/Release.key
  keyring: /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
  state: present


- name: Repositorio kubic
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04
    state: present

- name: Repositorio CRI-O
  repo: deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/
  state: present

- name: Instalación de CRI-O
  apt:
    pkg:
    - cri-o
    - cri-o-runc
